<html><head></head><body><div class="chapter" title="Chapter&#xA0;1.&#xA0;FreeCAD [How-to]"><div class="titlepage"><div><div><h1 class="title"><a id="ch01"/>Chapter 1. FreeCAD [How-to]</h1></div></div></div><p>Welcome to<span class="emphasis"><em> FreeCAD [How-to]</em></span>. This book will provide an introduction to the organization and versatility of this open source application. The recipes described in this book will introduce most of the concepts used throughout FreeCAD so that knowledge gained in one area will help you explore the other areas more efficiently.</p><p>FreeCAD is a general purpose modeling tool aimed at the engineering world. Unlike other modeling tools such as Blender or Maya, which are designed for animators and artists, FreeCAD puts heavy emphasis on parametric, feature-based design of three dimensional solids.</p><p>A great deal of foresight and planning has gone into the underlying technology of FreeCAD. The result is a tool that is powerful, easy to use, and easy to extend with the powerful scripting language Python.</p><p>This first part of this book will help you get familiar with the FreeCAD interface and philosophy. We'll look at a couple of specific techniques for modeling objects. The later recipes will focus more on using Python to automate and extend FreeCAD.</p><div class="section" title="Getting and installing FreeCAD (Must know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec01"/>Getting and installing FreeCAD (Must know)</h1></div></div></div><p>This recipe will describe the options available for installing FreeCAD on the three major platforms (Windows, Mac, and Linux). It will briefly cover the steps for installation of a stable release version.<a id="id0" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec01"/>Getting ready</h2></div></div></div><p>FreeCAD is still under heavy development. Stable releases are provided periodically that are tested and debugged. These releases will lack the most current features and may not match many of the recipes described in this book.</p><p>Detailed instructions are provided on the FreeCAD site for installation on all three platforms along with removal and troubleshooting information.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec02"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">For most casual users, the stable version binaries are the best place to start learning FreeCAD.</li><li class="listitem">Start by visiting the FreeCAD site at<a class="ulink" href="http://free-cad.sourceforge.net/"> http://free-cad.sourceforge.net/</a>.<a id="id1" class="indexterm"/></li><li class="listitem">The main page of the FreeCAD site has a panel with download links for the current stable release.<div class="mediaobject"><img src="graphics/8864_01_01.jpg" alt="How to do it..."/></div><div class="itemizedlist"><ul class="itemizedlist"><li class="listitem" style="list-style-type: disc">For Windows, the stable release is provided as a 32-bit Microsoft Installer application (<code class="literal">.msi</code> file). Download the file to your computer and double-click it to run the installation program.<a id="id2" class="indexterm"/></li><li class="listitem" style="list-style-type: disc">The Linux (<span class="strong"><strong>Ubuntu</strong></span>) link will direct you to a personal package archive (<code class="literal">PPA</code>). The packages here are for Ubuntu but should work on any recent Debian derived distribution. Both 32 and 64 bit versions are available through the PPA. Add the PPA to your repository manager and install it like any other application. FreeCAD is also available in the main Ubuntu repository, but this version is outdated and should be avoided.<a id="id3" class="indexterm"/></li><li class="listitem" style="list-style-type: disc">Mac OS X (Lion) is supported with a 64-bit installer package. The installer is distributed in a disk image. Download the disk image file. Mount it and run the<span class="emphasis"><em> Install FreeCAD</em></span> package. In the past, Mac OS X packaging was supported by only a small team and packages were not always up to date. OS X users are encouraged to consider building from source.<a id="id4" class="indexterm"/></li></ul></div></li></ol></div></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec03"/>There's more...</h2></div></div></div><p>FreeCAD's development pace is very fast. New features and improvements are appearing almost daily in the unstable and development branches of the source code. After you've explored the basics, you may wish to explore features not yet available in the stable version. Let's look at some of the other installation options.<a id="id5" class="indexterm"/>
</p><div class="section" title="Daily builds"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec01"/>Daily builds</h3></div></div></div><p>If you are using Linux and are willing to accept the risk of broken features and occasional crashes, you can install one of the daily builds. These are generated automatically by build scripts each day and consequently have had no formal testing. The daily build contains the most recent features and bug fixes committed to the source code by the developers.<a id="id6" class="indexterm"/>
</p><p>Daily builds aren't available for Windows but an unstable binary installer is periodically built. Download it from<a class="ulink" href="http://sourceforge.net/projects/free-cad/files/FreeCAD%20Windows/"> http://sourceforge.net/projects/free-cad/files/FreeCAD%20Windows/</a>.</p></div><div class="section" title="Building from source"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec02"/>Building from source</h3></div></div></div><p>Detailed instructions for building FreeCAD from source is beyond the scope of a How-to book, but an overview of the major steps may help:<a id="id7" class="indexterm"/>
</p><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem"><span class="strong"><strong> Meet the prerequisites:</strong></span> You'll need a compiler and all the dependency libraries. FreeCAD has a long list of dependencies and getting them all in place can be a chore. This is much easier on a Linux computer since most or all of the dependencies can be downloaded from the software manager.<a id="id8" class="indexterm"/><p>For Windows, the FreeCAD site also provides a libpack download to simplify the dependency requirements.
</p></li><li class="listitem"><span class="strong"><strong> Obtain the source code:</strong></span> FreeCAD source is maintained in a Git repository available at<code class="literal"> git://free-cad.git.sourceforge.net/gitroot/free-cad/free-cad</code>.<a id="id9" class="indexterm"/></li><li class="listitem"><span class="strong"><strong> Compiling:</strong></span> The specifics steps for compiling vary from platform to platform but are generally simple once the source and dependencies are in place. Study the page for your platform on the FreeCAD site.<a id="id10" class="indexterm"/></li></ol></div></div><div class="section" title="Third-party builds"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec03"/>Third-party builds</h3></div></div></div><p>The FreeCAD site also maintains a list of alternate builds. These are binary installations that are created and maintained by people and organizations outside the FreeCAD project. They may include custom features or may be optimized for specific operating systems. At the time of writing, there were third-party builds for OpenSuse, Fedora, Slackware, ArchLinux, Gentoo, and others.<a id="id11" class="indexterm"/>
</p></div></div></div></div>
<div class="section" title="Understanding the FreeCAD interface (Must know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec02"/>Understanding the FreeCAD interface (Must know)</h1></div></div></div><p>FreeCAD is designed to be flexible, extensible, and task oriented.</p><p>The core functionality is divided into<span class="strong"><strong> workbenches</strong></span>. Each workbench gathers the most frequently used tools for a particular task. This recipe will guide you through the FreeCAD user interface and introduce some concepts that are common across all workbenches.<a id="id12" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec04"/>Getting ready</h2></div></div></div><p>Launch FreeCAD and orient yourself with the screenshot and the names of the major parts of the interface. The images and examples in this book are from a 0.13 development snapshot.<a id="id13" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_02_01.jpg" alt="Getting ready"/></div><p>The default view is<span class="strong"><strong> Start page</strong></span> — an embedded browser showing interesting video links, examples, and other news.</p><p>The user interface is divided into three main areas:<a id="id14" class="indexterm"/>
</p><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">The 3D area allows you to see and navigate around your design in space.</li><li class="listitem">The combo view shows a hierarchical view of the project or the state of the current task.</li><li class="listitem">The tool bars and workbench switcher gives access to the various tools.</li></ol></div></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec05"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Open a new document by clicking on the menu<span class="strong"><strong> File | New</strong></span>. The 3D view will switch to show an empty space. In the default orientation the camera position is looking down onto a plane defined by the<span class="emphasis"><em> X</em></span> and<span class="emphasis"><em> Y</em></span> axes. The<span class="emphasis"><em> Z</em></span> axis is pointed directly at the camera. A coordinate indicator in the corner helps you orient yourself in the 3D space.<div class="mediaobject"><img src="graphics/8864_02_02.jpg" alt="How to do it..."/></div></li><li class="listitem">Click on the workbench switcher and select the<span class="strong"><strong> Part</strong></span> workbench. Then click on the<span class="strong"><strong> Create a box solid</strong></span> icon to insert a cube into the project.</li><li class="listitem">You can have multiple projects open at the same time. You can also open multiple views of the same project. Open a second view of the project by clicking on the menu<span class="strong"><strong> View | Create new view</strong></span>. You can switch views with the tabs below the 3D window or you can tile the views to have multiple perspectives at once. In this following screenshot, two projects are open, each with two views:<div class="mediaobject"><img src="graphics/8864_02_03.jpg" alt="How to do it..."/></div></li><li class="listitem">You can change the view of your project by<span class="strong"><strong> panning, rotating</strong></span>, and<span class="strong"><strong> zooming</strong></span>. Select objects by clicking on them to change their properties. The specific mouse and keyboard commands for doing this are called "navigation styles". FreeCAD supports four styles by default:<span class="emphasis"><em> Inventor, CAD, Blender</em></span>, and<span class="emphasis"><em> Touchpad</em></span>.<a id="id15" class="indexterm"/><p>You can change the style used in the current view by right-clicking on the 3D canvas.
</p><div class="mediaobject"><img src="graphics/8864_02_04.jpg" alt="How to do it..."/></div><p>Changing the style through the <span class="strong"><strong>Edit | Preferences</strong></span> menu will change the style for all views currently open and set the selection as the default for new views. The default style, <span class="strong"><strong>CAD navigation</strong></span>, is unintuitive for some users since it requires clicking both the left and center mouse buttons at the same time to rotate. The <span class="strong"><strong>Mouse...</strong></span> button in the <span class="strong"><strong>Display</strong></span> preferences will show which button combinations perform each action.
<a id="id16" class="indexterm"/>
</p></li><li class="listitem">Select the box and tap the space bar to toggle the object visibility property. Visibility is one of many properties of any object on screen. With the box still selected, examine the lower part of the combo-view. The properties of the selected object are shown on the two tabs (<span class="strong"><strong>View</strong></span> and<span class="strong"><strong> Data)</strong></span>.</li><li class="listitem">Click on the<span class="strong"><strong> Measure distance</strong></span> icon, and then click two points on the box in the 3D window. A dimension will be shown and a distance object will be added to the tree.<div class="mediaobject"><img src="graphics/8864_02_05.jpg" alt="How to do it..."/></div></li><li class="listitem">You can select the distance object in the tree and explore its properties.</li><li class="listitem">As the project complexity grows, you may need to perform an action on multiple objects at the same time. Select multiple objects by holding the<span class="emphasis"><em> Ctrl</em></span> key while selecting with the mouse.</li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec06"/>How it works...</h2></div></div></div><p>The<span class="strong"><strong> View/Data</strong></span> tabs reflect a deep design characteristic of FreeCAD. The data necessary to construct the object (size, type, placement, and rotation) is separated from the data needed to show it on screen (color, line style, visibility, and transparency).<a id="id17" class="indexterm"/>
</p><p>Most operations in FreeCAD are non-destructive and result in new objects being added to the project tree. Each new object has its own<span class="strong"><strong> View</strong></span> and<span class="strong"><strong> Data</strong></span> tabs and preserves its relationship to its simple precursor. This makes it possible to delete the later objects and revert to the simpler object if needed.</p><p>As objects are added and modified, they are organized in the combo-view tree in a hierarchical way. Generally, the last child object is displayed and parent objects are hidden automatically.</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec07"/>There's more...</h2></div></div></div><p>FreeCAD uses the term "view" to refer to several related concepts.</p><div class="section" title="Default views"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec04"/>Default views</h3></div></div></div><p>Eight default views are provided with icons in the tool bar to make it easy to position the project on the screen. These views are actually orientations of your work and shouldn't be confused with the view windows described previously.<a id="id18" class="indexterm"/>
</p><p>The term view also refers to the camera projection type:<span class="emphasis"><em> orthographic</em></span> or<span class="emphasis"><em> perspective</em></span>.</p></div><div class="section" title="Freezing and Saving views"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec05"/>Freezing and Saving views</h3></div></div></div><p>You can preserve a favorite orientation of your work by freezing it (Shift+F). This adds a menu item for the frozen view to let you easily return to this orientation later.<a id="id19" class="indexterm"/>
</p></div><div class="section" title="Python and Report views"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec06"/>Python and Report views</h3></div></div></div><p>FreeCAD has two other important windows that are hidden by default and that are confusingly also called "views". The Python console will be discussed at length in the later sections of this book. The Report views provide useful information about what FreeCAD is doing behind the scenes.<a id="id20" class="indexterm"/>
</p></div></div></div>
<div class="section" title="CSG modeling in the Part workbench (Must know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec03"/>CSG modeling in the Part workbench (Must know)</h1></div></div></div><p>
<span class="strong"><strong>Constructive Solid Geometry (CSG)</strong></span> is a modeling technique that combines primitive solids with Boolean operations to create more complex shapes. FreeCAD's CSG tools are found on the<span class="strong"><strong> Part workbench.</strong></span>
<a id="id21" class="indexterm"/>
</p><p>This recipe will use the Part workbench to model a simple part an offset mounting bracket for a NEMA 17 stepping motor.</p><div class="mediaobject"><img src="graphics/8864_03_01.jpg" alt="CSG modeling in the Part workbench (Must know)"/></div><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec08"/>Getting ready</h2></div></div></div><p>Create a new empty document and orient the view to the top using the<span class="strong"><strong> Set to top view</strong></span> top-view icon or by pressing the number<span class="emphasis"><em> 2</em></span>. Use the Workbench Changer to switch to the<span class="strong"><strong> Part</strong></span> workbench.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec09"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Model the bent metal plate by adding and positioning three box solids. Add the first box to the drawing, and select its node in the project tree. Switch to the<span class="strong"><strong> Data</strong></span> tab and edit the properties to make it 2.5 x 50 x 50 mm (height, length, width).<a id="id22" class="indexterm"/></li><li class="listitem">Create a second box with the same dimensions but edit the<span class="emphasis"><em> placement</em></span> to move the box 50 mm in the<span class="emphasis"><em> X</em></span> direction and 10 mm in the<span class="emphasis"><em> Z</em></span> direction. This will place the second cube next to the first and shifted upward.</li><li class="listitem">Add a third cube to connect them. Make its dimensions 10 x 2.5 x 50 mm and shift its placement 50 mm in the<span class="emphasis"><em> X</em></span> direction.</li><li class="listitem">If you rotate your view slightly, your three solids should look like the following figure:<div class="mediaobject"><img src="graphics/8864_03_02.jpg" alt="How to do it..."/></div></li><li class="listitem">Next we'll create the slots. FreeCAD doesn't have a slot feature so we'll make a solid in the shape of the hole we want. Later, we'll subtract it from the plate to create the hole.</li><li class="listitem">Add another box and set its dimensions to 10 x 10 x 3 mm.</li><li class="listitem">We want the slot to have rounded ends so we will fillet the box. Select the box and press the menu<span class="strong"><strong> Part | Fillet</strong></span>.</li><li class="listitem">The combo view will switch to the<span class="strong"><strong> Tasks</strong></span> panel and show the fillet options. You can use this to refine your edge selection and set the radius of the fillet. For our example, select<span class="strong"><strong> Edge1, Edge3, Edge5</strong></span>, and<span class="strong"><strong> Edge7</strong></span>. We used a value of 1 for the radius. Clicking on the<span class="strong"><strong> OK</strong></span> button will apply the change. If you make a mistake, double-click the fillet object in the tree to change the properties and try again.<a id="id23" class="indexterm"/></li><li class="listitem">Once the cube looks right, select it and duplicate it with the menu item<span class="strong"><strong> Edit | Duplicate selection</strong></span>. Repeat this twice more so that we have a total of four fillet objects. Select each one and change its placement properties to move it into position on the raised part of the plate. The position is up to you. Just make sure the fillet objects completely penetrate the plate.</li><li class="listitem">Now add five cylinders for the holes. Change their placement and radius properties. The center hole is 22.5 mm and the small screw holes are 2.5 mm.</li><li class="listitem">With all the solids added to the project, it should like the following image:<div class="mediaobject"><img src="graphics/8864_03_03.jpg" alt="How to do it..."/></div></li><li class="listitem">We're almost ready to subtract the cylinders and slots from our base plate, but we first need to clean things up a bit. In the project tree, select all of the cylinders and fillet objects. With all of them selected, click on the<span class="strong"><strong> Make a union of several shapes</strong></span> icon:<a id="id24" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_03_04.jpg" alt="How to do it..."/></div></li><li class="listitem">Now select the three boxes for our base plate and repeat the operation, fusing them into a single object.</li><li class="listitem">You should now have two fusion objects in the tree, one for the base plate and one for the holes that will be cut from it. First select the base plate fusion, and then with<span class="emphasis"><em> Ctrl</em></span> held down, select the other. Click on the<span class="strong"><strong> Make a cut of two shapes</strong></span> icon:<div class="mediaobject"><img src="graphics/8864_03_05.jpg" alt="How to do it..."/></div></li><li class="listitem">The order in which you select the objects is important. The first object will be cut by the second. If all goes well, you will have an object that looks almost like the image at the beginning of the recipe.</li><li class="listitem">To finish it off, we've applied another round of fillets to the corners of the plate and to the corners of the bend. The complete object should look like the image at the beginning of this recipe.<a id="id25" class="indexterm"/></li></ol></div></div><div class="section" title="How it works...."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec10"/>How it works....</h2></div></div></div><p>Union operations add objects together. The solids don't have to be touching or overlapping. After a union, they will have a single location and orientation.<a id="id26" class="indexterm"/>
</p><p>A difference Boolean cuts the first object with the second. If the two objects don't overlap, the original object will be unaffected.</p><p>An intersection eliminates everything except the area where the original two objects overlapped.</p><p>After any of these operations, a new object is created and the original items become its hidden children. You can delete the parent node and toggle the original object visible to get back to where you were. Objects such as fillet and chamfer can be double-clicked to reopen the dialog that created them and adjust the options.</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec11"/>There's more...</h2></div></div></div><p>There's often more than one way to do the same thing and the<span class="strong"><strong> Part</strong></span> workbench has a few hidden extras.</p><div class="section" title="Create primitives"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec07"/>Create primitives</h3></div></div></div><p>FreeCAD can create many more primitive types than those in the toolbar. Use the<span class="strong"><strong> Create primitives</strong></span> tool to create many other. For example, a spring-like parametric helix.<a id="id27" class="indexterm"/>
</p></div><div class="section" title="Why doesn't my part look right?"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec08"/>Why doesn't my part look right?</h3></div></div></div><p>If your part doesn't look like the example at the beginning of this recipe, try playing with the<span class="strong"><strong> View</strong></span> properties of the final object. Change the<span class="strong"><strong> Display Mode</strong></span> to<span class="strong"><strong> shaded</strong></span>.</p></div></div></div>
<div class="section" title="Recording and editing a macro (Should know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec04"/>Recording and editing a macro (Should know)</h1></div></div></div><p>Macros are commands that represent a series of commands or key strokes and can take the drudgery out of repetitive tasks. Macro recording can be used to automate tasks that don't warrant full blown script programming. This recipe will cover the steps required to record, edit, and run a macro.<a id="id28" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec12"/>Getting ready</h2></div></div></div><p>Locate the<span class="strong"><strong> Macro</strong></span> toolbar or<span class="strong"><strong> Macro</strong></span> menu item.<a id="id29" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_04_1.jpg" alt="Getting ready"/></div></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec13"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Press the red record button shown in the following screenshot:<div class="mediaobject"><img src="graphics/8864_04_2.jpg" alt="How to do it..."/></div></li><li class="listitem">The macro recording dialog box will pop up. Give your macro a name and save it:<div class="mediaobject"><img src="graphics/8864_04_3_2ndDraft.jpg" alt="How to do it..."/></div></li><li class="listitem">Perform the tasks that you want recorded. You can create a macro of whatever you normally do in FreeCAD. Macros that deal with simple part creation are easiest to start with. Try creating a box in the<span class="strong"><strong> Part</strong></span> workbench and change its width to 20 mm.<a id="id30" class="indexterm"/></li><li class="listitem">When you are done recording the tasks, press the green button to stop recording:<a id="id31" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_04_4.jpg" alt="How to do it..."/></div></li><li class="listitem">Run your macro by selecting the button that looks like a sketch pad:<div class="mediaobject"><img src="graphics/8864_04_5.jpg" alt="How to do it..."/></div></li><li class="listitem">Select the name of the macro that you created and click on<span class="strong"><strong> Execute:</strong></span><div class="mediaobject"><img src="graphics/8864_04_06_2ndDraft.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec14"/>How it works...</h2></div></div></div><p>In FreeCAD, macros are just a step-by-step representation of the commands that are saved as a Python script, with a FreeCAD macro file extension<code class="literal"> *.FCMacro</code>. As you perform tasks in FreeCAD, they have a corresponding Python command that is running in the background. A FreeCAD macro just captures those commands and saves them into a file that you can reuse.<a id="id32" class="indexterm"/>
</p><p>If you have problems saving macros, it could be because of a setting in macro preferences for FreeCAD. Open general preferences by clicking on<span class="strong"><strong> Edit</strong></span> |<span class="strong"><strong> Preferences | General</strong></span> and then click on the<span class="strong"><strong> Macro</strong></span> tab. Under<span class="strong"><strong> Macro recording settings</strong></span> the<span class="strong"><strong> Macro path</strong></span> should have a valid path to a file directory in it. If it doesn't, click on the button to the right of it and correct it with a valid directory name.</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec15"/>There's more...</h2></div></div></div><p>Most FreeCAD commands can be accessed with macros and Python scripting.</p><div class="section" title="Taking advantage of the power of macros"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec09"/>Taking advantage of the power of macros</h3></div></div></div><p>Macros actually record Python instructions as they are executed. We also have the ability to read and edit them later. Open our new macro with the<span class="strong"><strong> Edit</strong></span> button in the macro dialog. This will open our macro in FreeCAD's built-in macro editor. The following is our code:<a id="id33" class="indexterm"/>
</p><div class="informalexample"><pre class="programlisting"># Macro Begin: /home/freecad/10x10x20mm box.FCMacro ++
	import FreeCAD
	import Part
	
	#Gui.activateWorkbench("PartWorkbench")
	App.ActiveDocument.addObject("Part::Box","Box")
	#App.ActiveDocument.recompute()
	#Gui.SendMsgToActiveView("ViewFit")
	FreeCAD.getDocument("Unnamed").getObject("Box").Width = 20.00
	
	# Macro End: /home/freecad/10x10x20mm box.FCMacro ++
</pre></div><div class="note" title="Note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title"><a id="tip02"/>Tip</h3><p><span class="strong"><strong>Downloading the example code</strong></span></p><p>You can download the example code files for all Packt books you have purchased from your account at<a class="ulink" href="http://www.PacktPub.com"> http://www.PacktPub.com</a>. If you purchased this book elsewhere, you can visit<a class="ulink" href="http://www.PacktPub.com/support"> http://www.PacktPub.com/support</a> and register to have the files e-mailed directly to you.</p></div><p>The lines that begin with<code class="literal"> #</code> are not executed by FreeCAD; they are Python comments. Comments help us understand what is happening in the code. The only lines of code that are actually executed are as follows:<a id="id34" class="indexterm"/>
</p><div class="informalexample"><pre class="programlisting">import FreeCAD
	import Part
	
	App.ActiveDocument.addObject("Part::Box","Box")
	FreeCAD.getDocument("Unnamed").getObject("Box").Width = 20.00
</pre></div><p>The statements that start with<code class="literal"> import</code> open some major modules that are needed for our macro to be able to function.<code class="literal"> import Part</code> lets us make geometric objects such as boxes, cylinders, spheres, and a lot more.<code class="literal"> App.ActiveDocument.addObject("Part::Box","Box")</code> actually creates the box.</p><p>You can edit macros to do things that they didn't do originally, while they were being recorded. Open the macro in the built-in FreeCAD editor by pressing the button that looks like a text edit pad. Select your macro and then select the<span class="strong"><strong> Edit</strong></span> button. You could change the values of parameters for many different objects. In our example macro, you could change the following two lines to have a different name and length:</p><div class="informalexample"><pre class="programlisting">App.ActiveDocument.addObject("Part::Box","newbox")
	FreeCAD.getDocument("Unnamed").getObject("newbox").Width=20.5
</pre></div><p>Save your changes by selecting<span class="strong"><strong> File</strong></span> |<span class="strong"><strong> Save</strong></span> in the top menu. Then you can press the green playback icon to try out your altered macro:</p><div class="mediaobject"><img src="graphics/8864_04_7.jpg" alt="Taking advantage of the power of macros"/></div></div><div class="section" title="Learn a bit of Python programming by reading macro scripts"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec10"/>Learn a bit of Python programming by reading macro scripts</h3></div></div></div><p>Creating and editing macros is a good way of learning how to use Python within FreeCAD. Open your macros in the editor and play with them by changing different parameters and rerun them.<a id="id35" class="indexterm"/>
</p><p>To learn more about the Python programming language, go to<code class="literal"> http://docs.python.org/tutorial</code>.<a id="id36" class="indexterm"/>
</p></div></div></div>
<div class="section" title="Modeling a simple part with the Draft workbench (Must know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec05"/>Modeling a simple part with the Draft workbench (Must know)</h1></div></div></div><p>Many 3D designs begin as two dimensional drawings that are extruded or rotated into the third dimension. For example, a two dimensional square can be extruded into a three dimensional cube. The<span class="strong"><strong> Draft</strong></span> workbench provides tools for working with 2D geometry.<a id="id37" class="indexterm"/>
</p><p>In this recipe, we'll draw and edit a 2D profile of a part. In a later recipe, we'll rotate this profile to create a 3D model of a timing pulley.</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec16"/>Getting ready</h2></div></div></div><p>Start a new project and switch to the<span class="strong"><strong> Draft</strong></span> workbench. Make sure your view is set to top.<a id="id38" class="indexterm"/>
</p><p>Change your draft preferences to make it easier to snap to the grid. Set the<span class="strong"><strong> Grid spacing</strong></span> value to<code class="literal"> 1.000</code> and the<span class="strong"><strong> Main lines every</strong></span> value to<code class="literal"> 10</code>. Set the<span class="strong"><strong> Snap range</strong></span> to about<code class="literal"> 4px</code>.</p><div class="mediaobject"><img src="graphics/8864_05_01.jpg" alt="Getting ready"/></div></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec17"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Select the wire tool. Deselect the<span class="strong"><strong> Relative</strong></span> checkbox. Points of a wire can be added by clicking the canvas or manually by keying in coordinates. Manually enter the first point at X = 3.175, Y = -5, and Z = 0. You can<span class="emphasis"><em> Tab</em></span> from field to field and hit<span class="emphasis"><em> Enter</em></span> on Z to create the point.<a id="id39" class="indexterm"/></li><li class="listitem">Continue adding a second point at X = 3.175, Y = 10, Z = -0.</li><li class="listitem">Enter the remaining points working clockwise around until your wire looks like the following image. The remaining points can be added by clicking the canvas, and snapping to the grid if you prefer. Holding the<span class="emphasis"><em> Shift</em></span> key will force new segments to be orthogonal.</li></ol></div><p>When you have entered the last point but before returning to the starting point, click on<span class="strong"><strong> Close</strong></span> to automatically close the wire and exit the tool:<a id="id40" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_05_02.jpg" alt="How to do it..."/></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Before we can edit any part of the wire we have to explode it into a collection of edges. Select the wire in the project tree. Select the<span class="strong"><strong> Draft</strong></span> menu and click on the<span class="strong"><strong> Downgrade</strong></span> button three times.<a id="id41" class="indexterm"/></li><li class="listitem">We'll replace the square edge of the rim with a arc. Make sure that midpoint and endpoint are enabled on the snapping toolbar. Use the arc tool and draw a curve on the rim.<div class="mediaobject"><img src="graphics/8864_05_03.jpg" alt="How to do it..."/></div></li><li class="listitem">Repeat for the other rim, then delete the old straight edges.</li><li class="listitem">Select all the edges in the tree. Select the<span class="strong"><strong> Draft</strong></span> menu and click on the<span class="strong"><strong> Upgrade</strong></span> button to rejoin them into a wire.<a id="id42" class="indexterm"/></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec18"/>How it works...</h2></div></div></div><p>Complex topological shapes are built up from more simple geometric objects such as lines, circles, and arcs. For example, an<span class="strong"><strong> edge</strong></span> can be made from a line connecting two<span class="strong"><strong> vertices</strong></span>, each of which is a just a point in space. An edge can also be an arc or a circle. When multiple edges are connected end-to-end they become a<span class="strong"><strong> wire</strong></span>. A closed wire can be upgraded to a<span class="strong"><strong> face</strong></span>, and if a collection of faces fully encloses a volume it is a<span class="strong"><strong> solid</strong></span>. If a group of faces doesn't fully enclose the space (that is, one or more faces are missing) it is called a<span class="strong"><strong> shell</strong></span>.<a id="id43" class="indexterm"/>
</p><p>The<span class="strong"><strong> Draft</strong></span> workbench provides tools for directly creating, modifying, and converting between these data types.</p></div><div class="section" title="There's more...."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec19"/>There's more....</h2></div></div></div><p>In addition to the tools for creating and modifying 2D geometry, recent versions of the<span class="strong"><strong> Draft</strong></span> workbench have a couple of powerful and useful features.</p><div class="section" title="Create arrays"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec11"/>Create arrays</h3></div></div></div><p>The array tool creates arrays of individual objects. Polar arrays are useful for creating bolt circles and gears. Ortho arrays create grid-like arrangements.<a id="id44" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_05_04.jpg" alt="Create arrays"/></div><p>Select the object to be duplicated and click on the array tool. Then adjust the properties of the array in the<span class="strong"><strong> Data</strong></span> tab. These include the number of copies, rotation center, and array type.</p></div><div class="section" title="Converting drafts and sketches"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec12"/>Converting drafts and sketches</h3></div></div></div><p>A<span class="strong"><strong> sketch</strong></span> is another way of drawing 2D data in FreeCAD, which we'll be looking at in more detail in a later recipe. Sketches and drafts serve different purposes but it's sometimes desirable to convert between them. The Draft workbench has a tool for doing this conversion. Be aware that sketch-specific data will be lost when it's converted to a draft.<a id="id45" class="indexterm"/>
</p></div></div></div>
<div class="section" title="Rotating and extruding to create parts (Should know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec06"/>Rotating and extruding to create parts (Should know)</h1></div></div></div><p>2D drawings are converted into 3D models either by extruding them along an axis, or by rotating them around an axis.<a id="id46" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec20"/>Getting ready</h2></div></div></div><p>Use the<span class="strong"><strong> Draft</strong></span> workbench to draw a closed profile of a part. For our example, we're using the timing pulley profile from the<span class="emphasis"><em> Modeling a simple part with the Draft workbench (Must know)</em></span> recipe.<a id="id47" class="indexterm"/>
</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec21"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Switch to the<span class="strong"><strong> Draft</strong></span> workbench.</li><li class="listitem">Select the wire and click on the<span class="strong"><strong> Upgrade</strong></span> button to convert it to a face.</li><li class="listitem">Switch to the<span class="strong"><strong> Part</strong></span> workbench.<a id="id48" class="indexterm"/></li><li class="listitem">Press the<span class="strong"><strong> Revoke a selected shape</strong></span> button:<div class="mediaobject"><img src="graphics/8864_06_01.jpg" alt="How to do it..."/></div></li><li class="listitem">In the<span class="strong"><strong> Revolve</strong></span> dialog, select the shape to rotate.</li><li class="listitem">Select the axis around which to revolve. For our example, use the<span class="emphasis"><em> Y</em></span> axis. Leave the other settings unchanged and click on<span class="strong"><strong> OK</strong></span>.</li><li class="listitem">The revolved object is added to the project.<div class="mediaobject"><img src="graphics/8864_06_02.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec22"/>How it works...</h2></div></div></div><p>FreeCAD has two kinds of wire objects. Draft wires, called<span class="strong"><strong> dwire</strong></span> in later versions, have additional features and properties on the<span class="strong"><strong> Data</strong></span> tab. The wire used in our example contains arcs and is a regular wire. If you were to rotate the wire without upgrading it to a face first, the result you would see on screen would look exactly the same. However, the object would be a hollow shell. This can cause problems if you do additional Boolean operations. By rotating a face instead of a wire, the area swept out by the rotation is a solid.<a id="id49" class="indexterm"/>
</p><p>Extruding an object works similarly. A shape is selected and parameters are given for the direction and distance to extrude. Applying an extrusion to our original wire gives a very different result.</p><div class="mediaobject"><img src="graphics/8864_06_03.jpg" alt="How it works..."/></div><p>The extrude and rotate tools in the<span class="strong"><strong> Part</strong></span> workbench can be used on many kinds of objects including sketches. The kind of object produced depends on the original object.<a id="id50" class="indexterm"/>
</p><div class="informaltable"><table border="1"><colgroup><col style="text-align: left"/><col style="text-align: left"/></colgroup><thead><tr><th style="text-align: left" valign="bottom">
<p>Input shape</p>
</th><th style="text-align: left" valign="bottom">
<p>Output shape</p>
</th></tr></thead><tbody><tr><td style="text-align: left" valign="top">
<p>Vertex</p>
</td><td style="text-align: left" valign="top">
<p>Edge</p>
</td></tr><tr><td style="text-align: left" valign="top">
<p>Edge</p>
</td><td style="text-align: left" valign="top">
<p>Face</p>
</td></tr><tr><td style="text-align: left" valign="top">
<p>Wire (closed)</p>
</td><td style="text-align: left" valign="top">
<p>Shell</p>
</td></tr><tr><td style="text-align: left" valign="top">
<p>Dwire</p>
</td><td style="text-align: left" valign="top">
<p>Solid</p>
</td></tr><tr><td style="text-align: left" valign="top">
<p>Face</p>
</td><td style="text-align: left" valign="top">
<p>Solid</p>
</td></tr><tr><td style="text-align: left" valign="top">
<p>Shell</p>
</td><td style="text-align: left" valign="top">
<p>Compound Solid</p>
</td></tr><tr><td style="text-align: left" valign="top">
<p>Sketch</p>
</td><td style="text-align: left" valign="top">
<p>Shell</p>
</td></tr></tbody></table></div><p>The Part Design workbench has its own tools for rotating and extruding (called<span class="strong"><strong> padding)</strong></span> sketches to create parts. The Part Design pad and rotation tools can only be used on sketches. They always create solids if the sketch is closed and will fail otherwise.<a id="id51" class="indexterm"/>
</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec23"/>There's more...</h2></div></div></div><p>FreeCAD has another tool for turning 2D geometry into 3D objects.</p><div class="section" title="Lofting"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec13"/>Lofting</h3></div></div></div><p>Two or more wires can be used to define the bounds of a solid and the loft tool will create a solid by sweeping the area between them. In the following screenshot, two rectangular shapes were positioned one above the other and rotated slightly. The loft tool creates a twisted cuboid by connecting the two:<a id="id52" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_06_04.jpg" alt="Lofting"/></div></div></div></div>
<div class="section" title="Creating 3D solids with Python (Become an expert)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec07"/>Creating 3D solids with Python (Become an expert)</h1></div></div></div><p>Python is a high-level programming language that is easy to learn, easy to read, and powerful. To learn more about the Python programming language, go to<a class="ulink" href="http://www.python.org"> www.python.org</a>.<a id="id53" class="indexterm"/>
</p><p>FreeCAD's use of Python as its scripting language makes it extremely flexible for modeling parts. With Python in control, a user can do things that would be hard to do manually.</p><p>With this recipe, a model of a servo motor is rendered.</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec24"/>Getting ready</h2></div></div></div><p>For this recipe the Python console is needed. Make sure it's open. In the menu bar, click on<span class="strong"><strong> View | Views</strong></span> and then make sure<span class="strong"><strong> Python console</strong></span> is checked. The<span class="strong"><strong> Python console</strong></span> will be located in the bottommost panel in FreeCAD. It looks similar to the following screenshot:<a id="id54" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_07_00.jpg" alt="Getting ready"/></div><p>You will also need to have a document open in order for the Python scripted solid model to have a place to appear.</p><div class="note" title="Note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title"><a id="note03"/>Note</h3><p>Python is case sensitive. Make sure that you type in the following recipe exactly as it is shown. Python is also sensitive to indentation, so take care not to add extra spaces or tabs at the beginning of any line.</p></div></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec25"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Enter the following text into the Python console:<div class="informalexample"><pre class="programlisting">import Part
	from FreeCAD import Vector
	
	plate = Part.makeBox(40,40,5,Vector(-20,-20,0))
	hole1= Part.makeCylinder(1.5,5,Vector(-15,-15,0))
	hole2= Part.makeCylinder(1.5,5,Vector(-15,15,0))
	hole3= Part.makeCylinder(1.5,5,Vector(15,15,0))
	hole4= Part.makeCylinder(1.5,5,Vector(15,-15,0))
	faceplate = plate.cut(hole1)
	faceplate = faceplate.cut(hole2)
	faceplate = faceplate.cut(hole3)
	faceplate = faceplate.cut(hole4)
	motorbody=Part.makeCylinder(17.5,60,Vector(0,0,5))
	shaft = Part.makeCylinder(3.175,15,Vector(0,0,-15))
	servo = motorbody.fuse(faceplate)
	servo = servo.fuse(shaft)
	servo.translate(Vector(-20,-20,0))
	servo.rotate(Vector(0,0,0),Vector(0,1,0),-90)
	Part.show(servo)
</pre></div></li><li class="listitem">Make sure to press the<span class="emphasis"><em> Enter</em></span> key after the last line.</li><li class="listitem">You should see a 3D solid in the graphics screen of FreeCAD that looks similar to the following graphic:<a id="id55" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_07_01.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec26"/>How it works...</h2></div></div></div><p>At the start of the script, FreeCAD needs some of its modules imported:</p><div class="informalexample"><pre class="programlisting">import Part
	from FreeCAD import Vector
</pre></div><p>Without importing these, the script could not do anything beyond what is already in the standard Python library. The Part module gives access to geometric objects in FreeCAD. The Vector module is related to translating and rotating objects.</p><p>In lines like<code class="literal"> plate = Part.makeBox(40,40,5,Vector(-20,-20,0))</code> the Part module gives us a way of creating a solid box that is 40 mm x 40 mm x 5 mm big, which will be the face plate for our servo motor model. It is moved along a vector; 20 mm in the x direction; 20 mm in the y direction; and 0 mm in the z direction. FreeCAD allows us to create many types of solids in Python such as cylinders with<code class="literal"> Part.makeCylinder</code>, spheres with<code class="literal"> Part.makeSphere</code>, cones with<code class="literal"> Part.makeCone</code>, and toruses with<code class="literal"> Part.makeTorus</code>.</p><p>FreeCAD can cut 3D objects and fuse them to each other. In Python code that looks like this:<code class="literal"> faceplate = plate.cut(hole1)</code>, we are cutting the plate with<code class="literal"> hole1</code>. Fusing objects together can be seen in a line like<code class="literal"> servo = motorbody.fuse(faceplate)</code>, where motor body is fused to faceplate.<a id="id56" class="indexterm"/>
</p><p>At the end of the script, we make our servo motor visible by showing it using the following code:</p><div class="informalexample"><pre class="programlisting">	Part.show(servo)
</pre></div></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec27"/>There's more...</h2></div></div></div><p>You can use the Python console in FreeCAD to help you explore the depths of the the Part module. Just start typing<code class="literal"> Part</code>. into the console and FreeCAD's auto-completion feature will show you what classes are available and give you tips. The<code class="literal"> </code>. is what causes the console to auto complete.<a id="id57" class="indexterm"/>
</p><p>Here is what the auto completion feature looks like in action:</p><div class="mediaobject"><img src="graphics/8864_07_02.jpg" alt="There's more..."/></div><p>Notice how it gives you a helpful tip on the<code class="literal"> makeBox</code> class.</p><div class="section" title="Learn more about part scripting online"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec14"/>Learn more about part scripting online</h3></div></div></div><p>Go to<a class="ulink" href="http://https://sourceforge.net/apps/mediawiki/free-cad/index.php?title=Topological_data_scripting"> https://sourceforge.net/apps/mediawiki/free-cad/index.php?title=Topological_data_scripting</a> for more info and examples of how to work with Python in FreeCAD. More examples can also be found by searching<a class="ulink" href="http://www.thingiverse.com/"> http://www.thingiverse.com/</a> with the keyword<code class="literal"> freecad</code>.<a id="id58" class="indexterm"/>
</p></div></div></div>
<div class="section" title="Creating a custom dialog to automate a task (Become an expert)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec08"/>Creating a custom dialog to automate a task (Become an expert)</h1></div></div></div><p>The Python programming language in FreeCAD allows us to use PyQt4 or PySide to add our own widgets to make custom graphical user interfaces. In this recipe, we will create a dialog box that lets us create a simple box.<a id="id59" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec28"/>Getting ready</h2></div></div></div><p>If the<span class="strong"><strong> Draft</strong></span> workbench is functioning properly in FreeCAD, then you already have PyQt4 installed on your computer. Open a new document, so that we have space for our 3D box to appear.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec29"/>How to do it...</h2></div></div></div><p>The following is some code that will make a dialog pop-up, which lets us create a 3D solid box with a few parameters:</p><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Type the following code into the Python console exactly as shown. Python is case and indent sensitive. Be consistent on indentation. We will use four spaces per indent here. An intent looks like a tab in this text. I have added<code class="literal"> \</code> (backslashes) to some lines that won't fit on the printed page in their complete form.<div class="informalexample"><pre class="programlisting">	from PyQt4 import QtGui,QtCore
	import Part,FreeCAD
	from FreeCAD import Base,Vector
	
	class BoxExample(QtGui.QWidget):
	    def __init__(self):
	        super(BoxExample, self).__init__()
	        self.initUI()
	    def initUI(self):
	        self.setGeometry(100, 100,300, 200)
	        self.setWindowTitle('Make a Box!')
	        self.lengthLabel = QtGui.QLabel("Length: ",self)
	        self.lengthLabel.move(50, 15)
	        self.length = QtGui.QLineEdit(self)
	        self.length.move(100, 15)
	        self.widthLabel = QtGui.QLabel("Width: ",self)
	        self.widthLabel.move(50, 50)
	        self.width = QtGui.QLineEdit(self)
	        self.width.move(100, 50)
	        self.heightLabel = QtGui.QLabel("Height: ",self)
	        self.heightLabel.move(50, 85)
	        self.height = QtGui.QLineEdit(self)
	        self.height.move(100, 85)
	        self.centered=QtGui.QCheckBox("Center on XY",self)
	        self.centered.move(80, 115)
	        self.centerbox = False
	        self.centered.stateChanged.connect(self.changeState)
	        self.okButton = QtGui.QPushButton("Create Box",self)
	        self.okButton.move(160, 150)
	        self.show()
	        QtCore.QObject.connect \
	(self.okButton, QtCore.SIGNAL("pressed()"),self.box)  
	    def changeState(self, state):
	        console=FreeCAD.Console
	        if state == QtCore.Qt.Checked:
	            console.PrintMessage("Box will be centered\n")
	            self.centerbox = True
	        else:
	            self.centerbox = False
	    def box(self):
	        l = float(self.length.text())
	        w = float(self.width.text())
	        h = float(self.height.text())
	        if self.centerbox == True:
	            box = Part.makeBox(l,w,h)
	            box.translate(Base.Vector(-l/2,-w/2,0))
	        else:
	            box = Part.makeBox(l,w,h)
	        Part.show(box)
	
	d = BoxExample() 
</pre></div></li><li class="listitem">Press the<span class="emphasis"><em> Enter</em></span> key twice after typing in the last line.<a id="id60" class="indexterm"/></li><li class="listitem">When the dialog box pops up, fill in the values and click on the<span class="strong"><strong> Create Box</strong></span> button. A simple 3D box should appear in the FreeCAD document. It looks similar to the following screenshot:<a id="id61" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_08_01.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec30"/>How it works...</h2></div></div></div><p>We start by creating a class that holds all of our dialog box functions:</p><div class="informalexample"><pre class="programlisting">	<span class="strong"><strong>class BoxExample(QtGui.QWidget):
</strong></span>
</pre></div><p>The code within the<code class="literal"> BoxExample</code> class that is part of the function<code class="literal"> def initUI(self):</code> is used to set up the widgets for our dialog. Lines that have<code class="literal"> QtGui.QLabel</code> in them let us label the textboxes that are made with<code class="literal"> QtGui.QLineEdit(self)</code>. There is a checkbox and a button towards the end of the function in the form of<code class="literal"> QtGui.QCheckBox</code> and<code class="literal"> QtGui.QPushButton</code> respectively.<code class="literal"> def changeState(self, state):</code> is used to see if our<span class="strong"><strong> Center on XY</strong></span> checkbox is checked.<a id="id62" class="indexterm"/>
</p><p>The following lines of code are used to connect the button labeled<span class="strong"><strong> Create Box</strong></span> to the next function:</p><div class="informalexample"><pre class="programlisting"><span class="strong"><strong>QtCore.QObject.connect \
	(self.okButton, QtCore.SIGNAL("pressed()"),self.box)</strong></span>
</pre></div><p>I used the<code class="literal"> \</code> continuation character to fit one long line of code onto the formatted text of this book, so these two lines appear to be one to Python.</p><p>The<code class="literal"> def box(self)</code> function does the work to create the 3D solid box in the document.<code class="literal"> box = Part.makeBox(l,w,h)</code> creates the box and<code class="literal"> Part.show(box)</code> makes it appear in our document.<a id="id63" class="indexterm"/>
</p><p>Within FreeCAD Python scripting, we don't use a main call, like we would have if we were making a standalone application. Instead we use<code class="literal"> d = BoxExample()</code> to invoke and show our<code class="literal"> BoxExample()</code> class. This is what turns our dialog box on.<a id="id64" class="indexterm"/>
</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec31"/>There's more...</h2></div></div></div><p>To learn more about dialog creation for FreeCAD go to<a class="ulink" href="http://https://sourceforge.net/apps/mediawiki/free-cad/index.php?title=Dialog_creation"> https://sourceforge.net/apps/mediawiki/free-cad/index.php?title=Dialog_creation</a>.</p><div class="section" title="Learn more about Python and PyQt programming"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec15"/>Learn more about Python and PyQt programming</h3></div></div></div><p>One of the first places that a new Python programmer should check out is the official Python documentation website available at<a class="ulink" href="http://python.org/doc/"> http://python.org/doc/</a>.<a id="id65" class="indexterm"/>
</p><p>There is also a good intro to PyQt programming available at<a class="ulink" href="http://zetcode.com/tutorials/pyqt4/firstprograms/"> http://zetcode.com/tutorials/pyqt4/firstprograms/</a>.<a id="id66" class="indexterm"/>
</p></div><div class="section" title="Make things easier by using Qt Designer"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec16"/>Make things easier by using Qt Designer</h3></div></div></div><p>To make programming dialogs a lot easier, you will want to use Qt Designer, a graphical dialog creation tool. It will let you create dialogs with a graphical editor that can be converted into Python code. If you are using Ubuntu Linux as your operating system, look in Synaptic for<span class="strong"><strong> qtdesigner.</strong></span>
<a id="id67" class="indexterm"/>
</p><p>This following web page gives a good introduction to creating dialogs for FreeCAD:</p><p>
<a class="ulink" href="http://https://sourceforge.net/apps/mediawiki/free-cad/index.php?title=Dialog_creation">https://sourceforge.net/apps/mediawiki/free-cad/index.php?title=Dialog_creation</a>
</p></div></div></div>
<div class="section" title="Modeling with constraints (Must know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec09"/>Modeling with constraints (Must know)</h1></div></div></div><p>Many of the tools in the Part Design workbench will seem familiar from the Draft workbench. The workflow however is quite different. Built around the idea of feature-based design, geometry in the Part Design sketcher is first drawn very roughly and then refined with constraints. As the constraints are added, the built-in solver will adjust the geometry to satisfy the constraint requirements.<a id="id68" class="indexterm"/>
</p><p>In this recipe, we'll design a simple part that has features in two axes and show how it can be revised with constraints. In a later recipe, we'll add features to this part.</p><div class="mediaobject"><img src="graphics/8864_09_01.jpg" alt="Modeling with constraints (Must know)"/></div><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec32"/>Getting ready</h2></div></div></div><p>Begin with a new, empty document. Switch to the<span class="strong"><strong> Part Design</strong></span> workbench and click on the button to create a new or edit the selected sketch. A dialog will popup asking which plane you want the sketch oriented on. Select the<span class="strong"><strong> XZ-Plane</strong></span> option and click on<span class="strong"><strong> OK</strong></span>.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec33"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Roughly draw the end profile of the part. Don't worry about accuracy at this point. The following example was drawn with an arc and a wire:<div class="mediaobject"><img src="graphics/8864_09_02.jpg" alt="How to do it..."/></div></li><li class="listitem">Add geometric constraints. Constraints are added by selecting the parts of the sketch to be constrained and pressing the appropriate constraint button. A new constraint icon will be added to the drawing and it will be listed in the left-side panel.<a id="id69" class="indexterm"/></li><li class="listitem">Start by adding horizontal and vertical constraints to any crooked lines.<p>If lines are supposed to connect, select the vertexes and add coincident constraints.
</p><p>Select pairs of matching lines and add an equality constraint. This forces the lines to be equal length.
</p></li><li class="listitem">When the sketch looks symmetrical, add dimension constraints. Start by constraining the most important dimensions. For instance, we've constrained the radius of the arc to 25 mm.</li><li class="listitem">As you add constraints, watch the solver message at the top of the task panel. As the number of Degrees Of Freedom (DOF) approaches zero you may find it difficult to add constraints without getting a conflicting constraints error. Grabbing a vertex or segment and dragging it can show you where the sketch is still under constrained.</li><li class="listitem">If the sketch gets to 2 DOF and dragging a segment just moves the entire sketch, it's time to lock it. Pick a vertex (we used the center of the arc) and click on the lock button. This will add vertical and horizontal distance constraints which lock the vertex to the origin of the coordinate system. A fully constrained sketch will turn green. Celebrate.<div class="mediaobject"><img src="graphics/8864_09_03.jpg" alt="How to do it..."/></div></li><li class="listitem">Click on the<span class="strong"><strong> close</strong></span> button in the task panel. Use the pad tool to pad the sketch to 75 mm and rotate the sketch to see your part.<a id="id70" class="indexterm"/></li><li class="listitem">Even after the sketch has been padded, you can still edit it by double-clicking it in the tree. When saved, your changes will be immediately incorporated into the part.</li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec34"/>How it works...</h2></div></div></div><p>Constraints limit the ways in which an object can transform. A circle on a plane can be moved in two directions and can have its radius changed. Thus it has three degrees of freedom. When its radius is constrained it has 2 DOF and when its center is locked in X and Y, it is considered fully constrained.<a id="id71" class="indexterm"/>
</p><p>Geometric constraints are those that affect the shape or relationship of entities; horizontal, vertical, tangent, symmetric, and so on.<a id="id72" class="indexterm"/>
</p><p>Dimension constraints have a number. Double-click the constraint to edit the value. Length, radius, and angle are all dimension constraints.<a id="id73" class="indexterm"/>
</p><p>Modeling with constraints is very practical for discrete parts where the features have an implied relationship between them.</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec35"/>There's more...</h2></div></div></div><p>Avoiding and eliminating conflicting constraints is the biggest challenge most users face with the sketcher. Practice goes a long way towards improving your skills but following some basic guidelines will also help.<a id="id74" class="indexterm"/>
</p><div class="section" title="Apply constraints carefully"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec17"/>Apply constraints carefully</h3></div></div></div><p>Apply symmetry constraints first. Next apply geometric constraints (horizontal, vertical, tangent, and so on) before dimension constraints (anything with a number).<a id="id75" class="indexterm"/>
</p><p>When possible, fix the horizontal or vertical distance rather than constraining the length.</p><p>Try to apply coordinate locks last. In other words, try to get the sketch constrained with itself before you try to constrain it to the coordinate system.</p></div><div class="section" title="Use multiple simple sketches"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec18"/>Use multiple simple sketches</h3></div></div></div><p>It's generally easier to use several simple sketches to build up the complexity of your part rather than one large sketch with many constraints. Keep your sketches as simple as possible. Whenever possible, use chamfer and fillet operations on the solid rather than modeling the beveled or rounded corners in the sketch.<a id="id76" class="indexterm"/>
</p></div></div></div>
<div class="section" title="Using external constraints (Should know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec10"/>Using external constraints (Should know)</h1></div></div></div><p>It's rare that all the features of the part we want to design are in the same two-dimensional plane.<a id="id77" class="indexterm"/>
</p><p>Imagine that we want to add holes to the top surface of the part we designed in the<span class="emphasis"><em> Modeling with constraints (Must know)</em></span> recipe as shown in the following screenshot. To do this, we need a way to associate a new sketch with the top face of the part.<a id="id78" class="indexterm"/>
</p><p>An external constraint gives us a way to relate elements of our sketch to entities that are not in the sketch itself, like the face of a part.<a id="id79" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_10_01.jpg" alt="Using external constraints (Should know)"/></div><p>In this recipe we'll also show how features in a sketch can be related to an existing object.</p><p>Along the way, we'll also introduce construction lines and external constraints.<a id="id80" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec36"/>Getting ready</h2></div></div></div><p>This recipe uses functionality from FreeCAD version 0.13 and later. Make sure you are using a recent release or development snapshot.</p><p>Open the model created in the<span class="emphasis"><em> Modeling with constraints (Must know)</em></span> recipe. Set the view to<span class="strong"><strong> top</strong></span> so you're looking down on the part from above.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec37"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Select the top face of the part so it is highlighted and click on the sketch button. The new sketch will be mapped to the face.</li><li class="listitem">Draw four circles to represent our bolt holes. Select all four by clicking the edge (not the center) and set an equality constraint so they're the same size.</li><li class="listitem">Select one of the four and add a radius constraint. Set the radius to 3.5 mm. Now all four can be resized by changing one number.</li><li class="listitem">We want the holes to be positioned symmetrically. Select the centers of the top two holes and the vertical axis. Add a symmetry constraint. Repeat for the bottom two holes. The two sets of circles are now independently symmetrical.</li><li class="listitem">Draw a line from the center of the top-right hole to the center of the bottom-right hole. Make sure the end points are coincident with the center of each circle. Select the line and make it into a construction line by clicking on the construction mode icon.<div class="mediaobject"><img src="graphics/8864_10_02.jpg" alt="How to do it..."/></div></li><li class="listitem">Set a length constraint on the construction line of 50 mm.</li><li class="listitem">Now we need a way to set the position of the holes relative to the edge of the part.</li><li class="listitem">Click on the<span class="strong"><strong> External Constraint</strong></span> icon and select the right edge of the original solid. The edge and its vertexes can now be referenced in constraints as though they were a part of the sketch.<div class="mediaobject"><img src="graphics/8864_10_03.jpg" alt="How to do it..."/></div></li><li class="listitem">Select the center of the bottom-right circle and the bottom-end point of the external constraint line. Add a horizontal distance constraint (11 mm). Repeat and add a vertical distance constraint (15 mm).<a id="id81" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_10_04.jpg" alt="How to do it..."/></div></li><li class="listitem">The sketch should be fully constrained. To create holes all the way through the block, close the sketch and use the pocket tool. Set the pocket depth to at least 50 mm.</li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec38"/>How it works...</h2></div></div></div><p>Sketches can be drawn on the planar faces of existing solids to add features such as protrusions or recesses.</p><p>Construction geometry can be added to any sketch. These lines, circles, and arcs don't become part of the final object but can take all the same constraints. They assist in drawing other entities and establishing relationships between entities.</p><p>An external constraint line is similar to a construction line but is an edge selected from the face on which a sketch is being drawn.<a id="id82" class="indexterm"/>
</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec39"/>There's more...</h2></div></div></div><p>To use external constraints, a sketch must be mapped to a face. This happens automatically when you begin a sketch by selecting a face of an object. However, it is also possible to apply an existing sketch to a face on which it wasn't originally drawn.<a id="id83" class="indexterm"/>
</p><div class="section" title="Mapping a sketch to a face"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec19"/>Mapping a sketch to a face</h3></div></div></div><p>Select a face and click the menu<span class="strong"><strong> Part Design</strong></span> |<span class="strong"><strong> Map Sketch</strong></span> to face.<a id="id84" class="indexterm"/>
</p><p>In the dialog, select which sketch to map to the face and click on<span class="strong"><strong> OK</strong></span>. Mapping a sketch to the face puts the sketch into edit mode. Adjust the sketch if necessary and close it. A sketch can be remapped to a different face but cannot be mapped to multiple faces at the same time.</p></div></div></div>
<div class="section" title="Adding or modifying constraints with Python (Become an expert)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec11"/>Adding or modifying constraints with Python (Become an expert)</h1></div></div></div><p>In addition to using the Sketcher interactively and graphically we can use Python to program it automatically.<a id="id85" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec40"/>Getting ready</h2></div></div></div><p>For this recipe, we need the Python console open. In the menu bar, open<span class="strong"><strong> View</strong></span>, then<span class="strong"><strong> Views</strong></span>, and then make sure that<span class="strong"><strong> Python console</strong></span> is checked.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec41"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Enter the following code block into the console:<div class="informalexample"><pre class="programlisting">	from Sketcher import *  
	import Part
	import FreeCAD as App
	from FreeCAD import Vector
	if(App.activeDocument() == None):App.newDocument()
	
	f = App.activeDocument().addObject("Sketcher::SketchObject","Sketch")
	f.addGeometry(Part.Line(Vector(0,0,0),Vector(2,20,0)))
	f.addGeometry(Part.Line(Vector(0,0,0),Vector(20,2,0)))
	f.Constraints = [Constraint('Vertical',0),\ Constraint('Horizontal',1)]
	App.activeDocument().recompute()

</pre></div></li><li class="listitem">Double-click on the<span class="strong"><strong> Sketch</strong></span> icon in the Project tree.</li><li class="listitem">Notice the horizontal and vertical constraint symbols (the small red bars). Also notice that the lines have end points but they aren't constrained.<div class="mediaobject"><img src="graphics/8864_11_01.jpg" alt="How to do it..."/></div></li><li class="listitem">Grab either of the lines and move it and the other one won't move with it.<a id="id86" class="indexterm"/></li><li class="listitem">Add some more Python code to the console to constrain some points:<a id="id87" class="indexterm"/><div class="informalexample"><pre class="programlisting">StartPoint = 1 ;
	l = f.Constraints
	l.append(Constraint('Coincident',0,StartPoint,1,StartPoint))
	f.Constraints = l
	App.activeDocument().recompute()
</pre></div></li><li class="listitem">Notice how one end of each line has connected to the other.</li><li class="listitem">Try moving one of the lines around the screen and you will see that the lines move together.<div class="mediaobject"><img src="graphics/8864_11_02.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec42"/>How it works...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Import all available functions in the Sketcher module:<a id="id88" class="indexterm"/><div class="informalexample"><pre class="programlisting">	from Sketcher import *
</pre></div></li><li class="listitem">We will need the Part module to make geometric objects:<div class="informalexample"><pre class="programlisting">	import Part
</pre></div></li><li class="listitem">The FreeCAD module will let us manipulate the document:<div class="informalexample"><pre class="programlisting">	import FreeCAD as App
</pre></div></li><li class="listitem">We will need to give our line segments end points, so we need:<div class="informalexample"><pre class="programlisting">	from FreeCAD import Vector
</pre></div></li><li class="listitem">If a document isn't already open create a new one:<div class="informalexample"><pre class="programlisting">	if(App.activeDocument() == None): App.newDocument()
</pre></div></li><li class="listitem">Create a new Sketch object:<div class="informalexample"><pre class="programlisting">	f = App.activeDocument().addObject("Sketcher::SketchObject",\ "Sketch")
</pre></div></li><li class="listitem">Add geometry to the sketch:<div class="informalexample"><pre class="programlisting">f.addGeometry(Part.Line(Vector(0,0,0),Vector(2,20,0)))
	f.addGeometry(Part.Line(Vector(0,0,0),Vector(20,2,0)))
</pre></div></li><li class="listitem">Add some constraints to the sketch to make the lines horizontal and vertical:<a id="id89" class="indexterm"/><div class="informalexample"><pre class="programlisting">	f.Constraints = [Constraint('Vertical',0),\ Constraint('Horizontal',1)]
</pre></div></li><li class="listitem">Recompute the sketch to see things after changes:<a id="id90" class="indexterm"/><div class="informalexample"><pre class="programlisting">	App.activeDocument().recompute()
</pre></div></li><li class="listitem">Let's add a name for startpoints on our lines:<div class="informalexample"><pre class="programlisting">	StartPoint = 1
</pre></div></li><li class="listitem">Create a proxy object that is equal to our original, because we cannot add constraints directly to it:<a id="id91" class="indexterm"/><div class="informalexample"><pre class="programlisting">	l = f.Constraints
</pre></div></li><li class="listitem">Append more constraints to our proxy object.<code class="literal"> 0</code> is the first line and<code class="literal"> 1</code> is the second:<div class="informalexample"><pre class="programlisting">	l.append(Constraint('Coincident',0,StartPoint,1,StartPoint))
</pre></div></li><li class="listitem">Make the original constraints equal to the proxy and recompute:<div class="informalexample"><pre class="programlisting">	f.Constraints = l
	App.activeDocument().recompute()
</pre></div></li></ol></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl2sec43"/>There's more...</h3></div></div></div><p>You can constrain your geometry with dimensions, using Python.</p><div class="section" title="Add a length constraint to a line"><div class="titlepage"><div><div><h4 class="title"><a id="ch01lvl3sec20"/>Add a length constraint to a line</h4></div></div></div><p>You can add a length constraint to our second line as follows:<a id="id92" class="indexterm"/>
</p><div class="informalexample"><pre class="programlisting">	l.append((Constraint('DistanceX',1,20.0)))
</pre></div></div></div></div></div>
<div class="section" title="Creating a drawing of a part (Should know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec12"/>Creating a drawing of a part (Should know)</h1></div></div></div><p>The Drawing workbench lets us create 2D views of 3D objects for presentation in formats that are ideal for printing. In this recipe, we will create a drawing with three views.<a id="id93" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec44"/>Getting ready</h2></div></div></div><p>Select a 3D object in a document and open the<span class="strong"><strong> Drawing</strong></span> workbench:<a id="id94" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_12_01.jpg" alt="Getting ready"/></div></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec45"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">Select the<span class="strong"><strong> Insert new drawing</strong></span> icon:<div class="mediaobject"><img src="graphics/8864_12_02.jpg" alt="How to do it..."/></div></li><li class="listitem">Pick the<span class="emphasis"><em> Insert an orthographic projection</em></span> icon:<a id="id95" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_12_03.jpg" alt="How to do it..."/></div></li><li class="listitem">A new task will pop up in the<span class="strong"><strong> Task</strong></span> panel. Select a<span class="strong"><strong> Primary View:</strong></span><a id="id96" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_12_04.jpg" alt="How to do it..."/></div></li><li class="listitem">Select<span class="strong"><strong> Secondary Views:</strong></span><a id="id97" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_12_05.jpg" alt="How to do it..."/></div></li><li class="listitem">Click on the<span class="strong"><strong> OK</strong></span> button in the<span class="strong"><strong> Task</strong></span> panel.</li><li class="listitem">While the<span class="strong"><strong> Page</strong></span> icon is selected in the Project tree, click on its<span class="strong"><strong> Data</strong></span> tab.<a id="id98" class="indexterm"/></li><li class="listitem">Double-click on the button that has<span class="strong"><strong> ..</strong></span>. as its label.<div class="mediaobject"><img src="graphics/8864_12_06.jpg" alt="How to do it..."/></div></li><li class="listitem">A text dialog box will popup. Edit the values, putting in your name, the date, and so on:<a id="id99" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_12_07.jpg" alt="How to do it..."/></div></li><li class="listitem">Click on the recompute button to see the results:<a id="id100" class="indexterm"/><div class="mediaobject"><img src="graphics/8864_12_08.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec46"/>How it works...</h2></div></div></div><p>FreeCAD uses algorithms from the OpenCascade CAD kernel to calculate 2D projections from 3D objects. FreeCAD takes advantage of this and inserts those projections onto a SVG canvas. This canvas is actually a template that was imported during step 1.</p><p>The Orthographic Projection dialog in the Task panel creates different projections at set angles, scales them, and spaces them in a consistent way.</p><p>The text dialog helps us edit SVG editable texts and fills in the text information in the bottom-right corner of the title block.</p></div><div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec47"/>There's more...</h2></div></div></div><p>If you want to give your drawing to someone who doesn't have FreeCAD, you might want to export it as a PDF file.</p><div class="section" title="Export a PDF file from your drawing"><div class="titlepage"><div><div><h3 class="title"><a id="ch01lvl3sec21"/>Export a PDF file from your drawing</h3></div></div></div><p>Select the<span class="strong"><strong> Page</strong></span> object in the Project tree. From the top menu, select<span class="strong"><strong> File</strong></span> and then<span class="strong"><strong> Export PDF</strong></span>. Give your file a name with a<code class="literal"> *.pdf</code> extension and select a directory to save it to.</p></div></div></div>
<div class="section" title="Exporting DXF files for other applications (Should know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec13"/>Exporting DXF files for other applications (Should know)</h1></div></div></div><p>Most CAD applications don't live in a vacuum and need to be able to save to different file formats for other CADCAM programs to use. FreeCAD is no exception. There are some tasks that FreeCAD doesn't do especially well, such as dimensioning drawings. Other applications, such as LibreCAD or DraftSight do better in this area. Exporting 2D geometry to DXF format is an excellent way of facilitating this.<a id="id101" class="indexterm"/>
</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec48"/>Getting ready</h2></div></div></div><p>The first rule of exporting geometry is to make sure your geometry is clean and consistent. This means that the end points of lines and arcs that are meant to be connected should be connected with no gaps. Line segments hiding under other line segments should be deleted. Arcs and lines that are impossibly small should also be deleted. Don't leave any extra entities that aren't necessary in your document for exporting. 3D geometry does not export as DXF format in FreeCAD.</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec49"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">In the Project tree, select<span class="strong"><strong> 2D geometry</strong></span> from a<span class="strong"><strong> Sketch</strong></span> or the<span class="strong"><strong> Draft</strong></span> workbench. Be sure and select all geometry that you want exported.</li><li class="listitem">From the top menu, select<span class="strong"><strong> File</strong></span> and then<span class="strong"><strong> Export</strong></span>.</li><li class="listitem">In the lower-right corner of the<span class="strong"><strong> Export</strong></span> file dialog, select<span class="strong"><strong> Autodesk DXF</strong></span>.</li><li class="listitem">In the<span class="strong"><strong> Name</strong></span> entry box, give your file a name with the<code class="literal"> *.dxf</code> extension.</li><li class="listitem">Select the directory where you want your file saved.</li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec50"/>How it works...</h2></div></div></div><p>FreeCAD normally uses scripts from the<span class="strong"><strong> Draft</strong></span> workbench to export 2D geometry.<a id="id102" class="indexterm"/>
</p></div></div>
<div class="section" title="Importing data (Should know)"><div class="titlepage"><div><div><h1 class="title"><a id="ch01lvl1sec14"/>Importing data (Should know)</h1></div></div></div><p>Sometimes it is desirable to use geometry that was created in other CAD or modeling programs. FreeCAD can import a wide variety of file types. DXF, STEP, STL, SVG, VRML, Collada, and IDF are just some of the file formats that it can use.<a id="id103" class="indexterm"/>
</p><p>In this recipe, we will open a DXF file and use the geometry in it to form a 3D solid.</p><div class="section" title="Getting ready"><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec51"/>Getting ready</h2></div></div></div><p>You should have a DXF file produced by a CAD program such as QCAD, LibreCAD, Draftsight, or AutoCAD available to produce a DXF file.<a id="id104" class="indexterm"/>
</p><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">In FreeCAD, open the<span class="strong"><strong> Draft</strong></span> workbench and then select<span class="strong"><strong> Preferences</strong></span> from the<span class="strong"><strong> Edit</strong></span> menu.</li><li class="listitem">In the<span class="strong"><strong> Preferences</strong></span> dialog, click on the<span class="strong"><strong> Draft</strong></span> icon and then click on the<span class="strong"><strong> Import/Export</strong></span> tab.</li><li class="listitem">Under<span class="strong"><strong> DXF format options</strong></span>, change<span class="strong"><strong> Import style</strong></span> to<span class="strong"><strong> None (fastest)</strong></span>.</li><li class="listitem">Uncheck all the other boxes in that same section. Click on<span class="strong"><strong> Apply</strong></span> and then<span class="strong"><strong> OK</strong></span>.<div class="mediaobject"><img src="graphics/8864_14_01.jpg" alt="Getting ready"/></div></li></ol></div><p>Create some geometry in another CAD program. For this example, we will use DraftSight to create a simple shape. The following is a polyline rectangle with four fillets and a circle:<a id="id105" class="indexterm"/>
</p><div class="mediaobject"><img src="graphics/8864_14_02.jpg" alt="Getting ready"/></div><p>The lines and arcs in this drawing are a polyline. These will translate nicely into FreeCAD and help us create a solid to subtract the circle from.<a id="id106" class="indexterm"/>
</p><p>Save the file as an ASCII type<code class="literal"> dxf</code> (don't save as Binary).</p></div><div class="section" title="How to do it..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec52"/>How to do it...</h2></div></div></div><div class="orderedlist"><ol class="orderedlist arabic"><li class="listitem">In FreeCAD, select<span class="strong"><strong> Import</strong></span> from the<span class="strong"><strong> File</strong></span> menu.</li><li class="listitem">Select the<code class="literal"> dxf</code> file that you want to import.</li><li class="listitem">In the<span class="strong"><strong> Combo View</strong></span>, look at the<span class="strong"><strong> Project</strong></span> tab and expand the icons.<div class="mediaobject"><img src="graphics/8864_14_03.jpg" alt="How to do it..."/></div></li><li class="listitem">Switch to the<span class="strong"><strong> Draft</strong></span> workbench so that we can<span class="strong"><strong> Upgrade</strong></span> the Circle with the icon that looks like an arrow pointing upward.<a id="id107" class="indexterm"/></li><li class="listitem">Select the geometry labeled as<span class="strong"><strong> Polyline</strong></span> and use the<span class="strong"><strong> Part</strong></span> workbench with the<span class="strong"><strong> Extrude</strong></span> icon to extrude it into a solid.</li><li class="listitem">Extrude the geometry labeled<span class="strong"><strong> Circle</strong></span> into a solid. Make sure that its height is the same as the solid made from Polyline.</li><li class="listitem">Select the solid that you created from<span class="strong"><strong> Polyline</strong></span> and then the solid created by<span class="strong"><strong> Circle</strong></span>.</li><li class="listitem">Use the<span class="strong"><strong> Boolean Cut</strong></span> operation in<span class="strong"><strong> Part</strong></span> workbench to subtract the<span class="strong"><strong> Circle</strong></span> solid from the<span class="strong"><strong> Polyline</strong></span> solid.<div class="mediaobject"><img src="graphics/8864_14_04.jpg" alt="How to do it..."/></div></li></ol></div></div><div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch01lvl2sec53"/>How it works...</h2></div></div></div><p>DXF importing relies on code within the Draft workbench, so its settings are controlled from Draft preferences. The<code class="literal"> dxf</code> polyline imported in as a face that could be extruded in the Part workbench. The Draft workbench has tools for changing other 2D geometry into faces, using the Upgrade tool, which allows the Part workbench to make solids from them. Faces will extrude as solids, whereas a closed shape without a face will just extrude into a thin object that looks like walls.<a id="id108" class="indexterm"/>
</p></div></div></body></html>